### ISSUE TITLE
Wallet 1.1.0.2 doesn't start on OS-X

### ISSUE THREAD

**Issue by iSnow** [GiantPay/GiantCore#1]
Snows-Air:~ snow$ /Applications/giant-1.1.0.2-osx/giant-qt ; exit;
dyld: Library not loaded: /usr/local/opt/zeromq/lib/libzmq.5.dylib
  Referenced from: /Applications/giant-1.1.0.2-osx/giant-qt
  Reason: image not found
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by GiantPay** [comment]
You need to install the required libraries, for example with the help of brew

brew install zeromq

We will write a guide to launch a wallet under the OS-X - https://trello.com/c/DHIkQssa/19-guide-on-how-to-run-a-wallet-on-macos

**Comment by GiantPay** [comment]
We builded DMG file https://github.com/GiantPay/GiantCore/releases/tag/1.1.0.3
