### ISSUE TITLE
Errors in the source code.

### ISSUE THREAD

**Issue by Krot666** [GiantPay/GiantCore#3]
The **make** command does not work, although the first two teams were successful.
![screenshot_2](https://user-images.githubusercontent.com/33595988/43033340-0b3c75a6-8cf3-11e8-975a-03db52f86fb0.png)

**Comment by GiantPay** [comment]
./configure ended with an error. On the screen you can see it

error: Found Berkeley DB other than 4.8, required ....

Please read the instructions https://github.com/GiantPay/GiantCore/blob/master/doc/build-unix.md

**Comment by Krot666** [comment]
Why can not you make files where the latest version of the library is used?
