### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by ghost** [GiantPay/GiantCore#7]
OS: Ubuntu 16.04

Execute `giant-cli getblocktemplate` show error

    error: {"code":-7,"message":"Out of memory"}

`giant-cli getinfo`

    {
        "version" : 1010100,
        "protocolversion" : 10100,
        "walletversion" : 61000,
        "balance" : 0.50506318,
        "Darksend_balance" : 0.00000000,
        "blocks" : 82391,
        "timeoffset" : 0,
        "connections" : 12,
        "proxy" : "",
        "difficulty" : 37636.61008632,
        "testnet" : false,
        "keypoololdest" : 1522820148,
        "keypoolsize" : 1001,
        "paytxfee" : 0.00000000,
        "relayfee" : 0.00010000,
        "staking status" : "Staking Not Active",
        "errors" : ""
    }

**Comment by GiantCoreDev** [comment]
1. You are using an outdated version. The last is 1.2.2.0
2. Giant network uses the consensus Proof of Stake from block 71401
